- title: Strategy & Product
  excerpt: "We help teams figure out what to do in the first place, through
    product design or ideation. Our expertise extends to product development,
    Open Data and elections."
  icon: strategy
- title: UI & UX Design
  excerpt: "We invest early into designing a user experience that will work for
    our users, guiding teams through our process all the way up to polishing
    interfaces that are delighful to use."
  icon: strategy
- title: Web & mobile development
  excerpt: "We use the right tools for the right job to build Web, iOS, Android
    & desktop apps. This includes Python, Node.js, Go, React, AngularJS, D3.js,
    Rust and whole bunch of other things."
  icon: strategy
- title: DevOps
  excerpt: "May this be implementing autoscaling with Ansible, using Docker for
    deployment and testing, or bridging the gap between development and ops teams
    with ChatOps, we just ♥ infrastructure."
- title: API
  icon: strategy
- title: Data science
  icon: strategy
